-- ⚠️  ARQUIVO DEPRECIADO
-- Os fixes deste patch (payment = 'cartao_credito' na view e na função liquidar_fatura)
-- foram incorporados ao schema.sql consolidado.
-- Execute apenas: supabase/schema.sql
